CREATE TABLE [dbo].[ORDENES]
(
[ORDENID] [int] NOT NULL,
[EMPLEADOID] [int] NOT NULL,
[CLIENTEID] [int] NOT NULL,
[FECHAORDEN] [datetime] NOT NULL,
[DESCUENTO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDENES] ADD CONSTRAINT [PK_ORDENES] PRIMARY KEY NONCLUSTERED  ([ORDENID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDENES] ADD CONSTRAINT [FK_ORDENES_CLIEN_ORD_CLIENTES] FOREIGN KEY ([CLIENTEID]) REFERENCES [dbo].[CLIENTES] ([CLIENTEID])
GO
ALTER TABLE [dbo].[ORDENES] ADD CONSTRAINT [FK_ORDENES_EMPLE_ORD_EMPLEADO] FOREIGN KEY ([EMPLEADOID]) REFERENCES [dbo].[EMPLEADOS] ([EMPLEADOID])
GO
