CREATE TABLE [dbo].[PROVEEDORES]
(
[PROVEEDORID] [int] NOT NULL,
[NOMBREPROV] [char] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CONTACTO] [char] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CELUPROV] [char] (12) COLLATE Modern_Spanish_CI_AS NULL,
[FIJOPROV] [char] (12) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROVEEDORES] ADD CONSTRAINT [PK_PROVEEDORES] PRIMARY KEY NONCLUSTERED  ([PROVEEDORID]) ON [PRIMARY]
GO
