CREATE TABLE [dbo].[CLIENTES]
(
[CLIENTEID] [int] NOT NULL,
[CEDULA_RUC] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMBRECIA] [char] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMBRECONTACTO] [char] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRECCIONCLI] [char] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FAX] [char] (12) COLLATE Modern_Spanish_CI_AS NULL,
[EMAIL] [char] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CELULAR] [char] (12) COLLATE Modern_Spanish_CI_AS NULL,
[FIJO] [char] (12) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTES] ADD CONSTRAINT [PK_CLIENTES] PRIMARY KEY NONCLUSTERED  ([CLIENTEID]) ON [PRIMARY]
GO
