CREATE TABLE [dbo].[DETALLE_ORDENES]
(
[ORDENID] [int] NOT NULL,
[DETALLEID] [int] NOT NULL,
[PRODUCTOID] [int] NOT NULL,
[CANTIDAD] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLE_ORDENES] ADD CONSTRAINT [PK_DETALLE_ORDENES] PRIMARY KEY NONCLUSTERED  ([ORDENID], [DETALLEID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLE_ORDENES] ADD CONSTRAINT [FK_DETALLE__ORDEN_DET_ORDENES] FOREIGN KEY ([ORDENID]) REFERENCES [dbo].[ORDENES] ([ORDENID])
GO
ALTER TABLE [dbo].[DETALLE_ORDENES] ADD CONSTRAINT [FK_DETALLE__PROD_DETA_PRODUCTO] FOREIGN KEY ([PRODUCTOID]) REFERENCES [dbo].[PRODUCTOS] ([PRODUCTOID])
GO
