CREATE TABLE [dbo].[CATEGORIAS]
(
[CATEGORIAID] [int] NOT NULL,
[NOMBRECAT] [char] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIAS] ADD CONSTRAINT [PK_CATEGORIAS] PRIMARY KEY NONCLUSTERED  ([CATEGORIAID]) ON [PRIMARY]
GO
