CREATE TABLE [dbo].[EMPLEADOS]
(
[EMPLEADOID] [int] NOT NULL,
[NOMBRE] [char] (30) COLLATE Modern_Spanish_CI_AS NULL,
[APELLIDO] [char] (30) COLLATE Modern_Spanish_CI_AS NULL,
[FECHA_NAC] [datetime] NULL,
[REPORTA_A] [int] NULL,
[EXTENSION] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create trigger [dbo].[reemplazo]
on [dbo].[EMPLEADOS]
instead of insert as
print 'no hay contrataciones'
GO
ALTER TABLE [dbo].[EMPLEADOS] ADD CONSTRAINT [PK_EMPLEADOS] PRIMARY KEY NONCLUSTERED  ([EMPLEADOID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLEADOS] ADD CONSTRAINT [FK_EMPLEADO_REPORTA] FOREIGN KEY ([REPORTA_A]) REFERENCES [dbo].[EMPLEADOS] ([EMPLEADOID])
GO
